name: prose linting
on:
  pull_request:

jobs:
  lint-docs:
    name: Lint documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: errata-ai/vale-action@reviewdog
        with:
          files: content/en/docs
          fail_on_error: true
